apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "petstore.name" . }}
  labels: {{- include "petstore.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "petstore.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "petstore.labels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: {{ (first .Values.ports).port | quote }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
        - name: {{ include "petstore.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            {{- range .Values.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "petstore.name" . }}
            {{- if .Values.database.enabled }}
            - secretRef:
                name: {{ .Values.database.secretName }}
            {{- end }}
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            periodSeconds: 5
            failureThreshold: 3
          resources: {{- toYaml .Values.resources | nindent 12 }}
