apiVersion: v1
kind: Service
metadata:
  name: {{ include "petstore.name" . }}
  labels: {{- include "petstore.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "petstore.selectorLabels" . | nindent 4 }}
  ports:
    {{- range .Values.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .name }}
    {{- end }}
